<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Janusz-Kossowski-mac.local" name="Command line test" tests="4" failures="3" timestamp="20 Feb 2016 03:06:40 GMT" time="772.266" errors="0">
  <testcase name="powtorneWydanieNaBudoweTest" time="0.051" classname="org.kossowski.elemont.domain.operacje.WydanieNabudoweTest">
    <failure type="org.testng.TestException" message="
Expected exception org.kossowski.elemont.domain.IllegalStatusException but got org.testng.TestException: 
Expected exception org.kossowski.elemont.domain.IllegalStatusException but got java.lang.AssertionError: expected [Stan{stan=[ 0=&amp;gt;100,  1=&amp;gt;50,  2=&amp;gt;50,  3=&amp;gt;0,  4=&amp;gt;0,  5=&amp;gt;0,  6=&amp;gt;0,  7=&amp;gt;0  ]}] but found [Stan{stan=[ 0=&amp;gt;100,  1=&amp;gt;50,  2=&amp;gt;50,  3=&amp;gt;0,  4=&amp;gt;0,  5=&amp;gt;0,  6=&amp;gt;0,  7=&amp;gt;50  ]}]">
      <![CDATA[org.testng.TestException: 
Expected exception org.kossowski.elemont.domain.IllegalStatusException but got java.lang.AssertionError: expected [Stan{stan=[ 0=>100,  1=>50,  2=>50,  3=>0,  4=>0,  5=>0,  6=>0,  7=>0  ]}] but found [Stan{stan=[ 0=>100,  1=>50,  2=>50,  3=>0,  4=>0,  5=>0,  6=>0,  7=>50  ]}]
Expected exception org.kossowski.elemont.domain.IllegalStatusException but got java.lang.AssertionError: expected [Stan{stan=[ 0=>100,  1=>50,  2=>50,  3=>0,  4=>0,  5=>0,  6=>0,  7=>0  ]}] but found [Stan{stan=[ 0=>100,  1=>50,  2=>50,  3=>0,  4=>0,  5=>0,  6=>0,  7=>50  ]}]
	... 25 more
Caused by: java.lang.AssertionError: expected [Stan{stan=[ 0=>100,  1=>50,  2=>50,  3=>0,  4=>0,  5=>0,  6=>0,  7=>0  ]}] but found [Stan{stan=[ 0=>100,  1=>50,  2=>50,  3=>0,  4=>0,  5=>0,  6=>0,  7=>50  ]}]
	at org.kossowski.elemont.domain.operacje.WydanieNabudoweTest.powtorneWydanieNaBudoweTest(WydanieNabudoweTest.java:86)
	... 27 more
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- powtorneWydanieNaBudoweTest -->
  <testcase name="wydanieNaBudoweTest" time="772.155" classname="org.kossowski.elemont.domain.operacje.WydanieNabudoweTest">
    <failure type="java.lang.AssertionError" message="expected [Stan{stan=[ 0=&amp;gt;100,  1=&amp;gt;0,  2=&amp;gt;100,  3=&amp;gt;0,  4=&amp;gt;0,  5=&amp;gt;0,  6=&amp;gt;0,  7=&amp;gt;0  ]}] but found [Stan{stan=[ 0=&amp;gt;100,  1=&amp;gt;0,  2=&amp;gt;100,  3=&amp;gt;0,  4=&amp;gt;0,  5=&amp;gt;0,  6=&amp;gt;0,  7=&amp;gt;100  ]}]">
      <![CDATA[java.lang.AssertionError: expected [Stan{stan=[ 0=>100,  1=>0,  2=>100,  3=>0,  4=>0,  5=>0,  6=>0,  7=>0  ]}] but found [Stan{stan=[ 0=>100,  1=>0,  2=>100,  3=>0,  4=>0,  5=>0,  6=>0,  7=>100  ]}]
	at org.kossowski.elemont.domain.operacje.WydanieNabudoweTest.wydanieNaBudoweTest(WydanieNabudoweTest.java:68)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- wydanieNaBudoweTest -->
  <testcase name="wydanieNaBudoweTest1" time="0.0" classname="org.kossowski.elemont.domain.operacje.WydanieNabudoweTest"/>
  <testcase name="wydanieWithNull" time="0.001" classname="org.kossowski.elemont.domain.operacje.WydanieNabudoweTest">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.NullPointerException but got org.testng.TestException: 
Method WydanieNabudoweTest.wydanieWithNull()[pri:0, instance:org.kossowski.elemont.domain.operacje.WydanieNabudoweTest@67b467e9] should have thrown an exception of class java.lang.NullPointerException">
      <![CDATA[org.testng.TestException: 
Method WydanieNabudoweTest.wydanieWithNull()[pri:0, instance:org.kossowski.elemont.domain.operacje.WydanieNabudoweTest@67b467e9] should have thrown an exception of class java.lang.NullPointerException
Method WydanieNabudoweTest.wydanieWithNull()[pri:0, instance:org.kossowski.elemont.domain.operacje.WydanieNabudoweTest@67b467e9] should have thrown an exception of class java.lang.NullPointerException
	... 25 more
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- wydanieWithNull -->
</testsuite> <!-- Command line test -->
